/**
 * Precomputes the world-map geometry (land/graticule/sphere paths, projected
 * node coordinates, route arcs) into a static module, so the browser never
 * loads d3-geo, topojson-client or the world-atlas dataset at runtime.
 *
 * Runs automatically as part of `npm run build`.
 */
import { writeFileSync } from 'fs';
import { networkGeometry } from '../src/lib/config/network-geometry';

const contents =
  `// AUTO-GENERATED by scripts/gen-geometry.ts — do not edit by hand.\n` +
  `// Regenerated on each build. Contains only serialized geometry (no libs).\n` +
  `import type { NetworkGeometry } from './network-geometry-types';\n\n` +
  `export const networkGeometry: NetworkGeometry = ${JSON.stringify(networkGeometry)};\n`;

writeFileSync('src/lib/config/network-geometry-static.ts', contents);
console.log('Generated src/lib/config/network-geometry-static.ts');
console.log(`canvas: ${networkGeometry.W}x${networkGeometry.H}`);
// Key coordinates used to hand-tune the responsive viewBox crops.
for (const id of ['istanbul', 'london', 'moscow', 'dubai', 'hongkong', 'singapore', 'newyork', 'losangeles', 'tokyo']) {
  const p = networkGeometry.nodeXY[id];
  if (p) console.log(`  ${id}: ${Math.round(p.x)},${Math.round(p.y)}`);
}
